api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url

from rest_framework import routers

from api.views import UserViewSet
from api.views import SampleViewSet


router = routers.DefaultRouter()
router.register(r'account', UserViewSet)
router.register(r'sample', SampleViewSet)

# urlpatterns for API endpoints
urlpatterns = patterns('',
    url(r'^v1/', include(router.urls)),
)

samples/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import url

from samples.views import SampleList
from samples.views import SampleUpload
from samples.views import SampleDelete
from samples.views import SampleDetail
from samples.views import SampleUpdate
from samples.views import SampleDownload
from samples.views import FilenameDelete
from samples.views import FilenameRemove
from samples.views import FilenameAppend
from samples.views import HyperlinkAppend
from samples.views import HyperlinkRemove
from samples.views import HyperlinkDelete
from samples.views import SourceAppend
from samples.views import DescriptionCreate
from samples.views import DescriptionDelete
from samples.views import DescriptionUpdate
from samples.views import SourceList
from samples.views import SourceCreate
from samples.views import SourceUpdate
from samples.views import SourceDelete
from samples.views import SourceDetail
from samples.views import SourceRemove


urlpatterns = patterns('',
    url(
        r'^source/list/$',
        SourceList,
        name='source.list'
    ),
    url(
        r'^source/create/$',
        SourceCreate,
        name='source.create'
    ),
    url(
        r'^source/update/(?P<pk>\d+)/$',
        SourceUpdate,
        name='source.update'
    ),
    url(
        r'^source/delete/(?P<pk>\d+)/$',
        SourceDelete,
        name='source.delete'
    ),
    url(
        r'^source/detail/(?P<pk>\d+)/$',
        SourceDetail,
        name='source.detail'
    ),
)

urlpatterns += patterns('',
    url(
        r'^list/$',
        SampleList,
        name='sample.list'
    ),
    url(
        r'^upload/$',
        SampleUpload,
        name='sample.upload'
    ),
    url(
        r'^download/(?P<sha256>[\w]+)$',
        SampleDownload,
        name='sample.download'
    ),
    url(
        r'^delete/(?P<sha256>[\w]+)$',
        SampleDelete,
        name='sample.delete'
    ),
    url(
        r'^profile/(?P<sha256>[\w]+)$',
        SampleDetail,
        name='sample.detail'
    ),
    url(
        r'^update/(?P<sha256>[\w]+)$',
        SampleUpdate,
        name='sample.update'
    ),
    url(
        r'^filename/delete/(?P<pk>\d+)$',
        FilenameDelete,
        name='filename.delete'
    ),
    url(
        r'^filename/remove/(?P<sha256>[\w]+)/(?P<filename_pk>\d+)$',
        FilenameRemove,
        name='filename.remove'
    ),
    url(
        r'^filename/append/(?P<sha256>[\w]+)$',
        FilenameAppend,
        name='filename.append'
    ),
    url(
        r'^hyperlink/append/(?P<sha256>[\w]+)$',
        HyperlinkAppend,
        name='hyperlink.append'
    ),
    url(
        r'^hyperlink/remove/(?P<sha256>[\w]+)/(?P<hyperlink_pk>\d+)$',
        HyperlinkRemove,
        name='hyperlink.remove'
    ),
    url(
        r'^hyperlink/delete/(?P<pk>\d+)$',
        HyperlinkDelete,
        name='hyperlink.delete'
    ),
    url(
        r'^source/append/(?P<sha256>[\w]+)$',
        SourceAppend,
        name='source.append'
    ),
    url(
        r'^source/remove/(?P<sha256>[\w]+)/(?P<source_pk>\d+)$',
        SourceRemove,
        name='source.remove'
    ),
    url(
        r'^descr/create/(?P<sha256>[\w]+)$',
        DescriptionCreate,
        name='descr.create'
    ),
    url(
        r'^descr/delete/(?P<pk>\d+)$',
        DescriptionDelete,
        name='descr.delete'
    ),
    url(
        r'^descr/update/(?P<pk>\d+)$',
        DescriptionUpdate,
        name='descr.update'
    ),
)

samples/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse_lazy
from django.core.validators import URLValidator

from core.models import TimeStampedModel


class Source(TimeStampedModel):

    """
    Source model stores information of sample sources.
    """

    name = models.CharField(max_length=255)
    link = models.URLField(null=True, blank=True)
    descr = models.TextField(null=True, blank=True)
    user = models.ForeignKey('auth.User')

    def __unicode__(self):
        return '{0}'.format(self.name)

    def get_absolute_url(self):
        return reverse_lazy('source.detail', args=[self.pk])

    class Meta:
        ordering = ['name']
        # every user can create own sources
        unique_together = ('user', 'name')


class Filename(TimeStampedModel):

    """
    This models saves filename. A sample might have various filename,
    a filename might map to samples.
    """

    name = models.CharField(max_length=255)
    user = models.ForeignKey('auth.User')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['-created']
        unique_together = ('user', 'name')


class Filetype(TimeStampedModel):

    """
    This models saves filetype.
    """

    filetype = models.CharField(max_length=255)
    detector = models.CharField(max_length=255)

    def __unicode__(self):
        return '{0} {1}'.format(self.detector, self.filetype)

    class Meta:
        ordering = ['filetype']
        unique_together = ('filetype', 'detector')


class Hyperlink(TimeStampedModel):

    """
    This model saves sample's links.
    Download links, report links or related links.
    """

    KIND_CHOICES = (
        (0, 'Download Link'),
        (1, 'Analysis Report Link'),
        (2, 'Other'),
    )

    link = models.TextField(validators=[URLValidator()])
    headline = models.CharField(max_length=255, null=True, blank=True)
    kind = models.IntegerField(max_length=2, choices=KIND_CHOICES, default=0)
    user = models.ForeignKey('auth.User')

    def __unicode__(self):
        return "[{0}]({1})".format(self.headline, self.link)

    class Meta:
        ordering = ['kind', '-created']


class Sample(TimeStampedModel):

    """
    Sample model stores attributes of a sample
    """

    md5 = models.CharField(max_length=32)
    sha1 = models.CharField(max_length=40)
    sha256 = models.CharField(max_length=64)
    sha512 = models.CharField(max_length=128)
    ssdeep = models.CharField(max_length=255)
    size = models.IntegerField(default=0)
    crc32 = models.IntegerField(max_length=255)
    filetypes = models.ManyToManyField(Filetype, null=True, blank=True)
    filenames = models.ManyToManyField(Filename, null=True, blank=True)
    sources = models.ManyToManyField(Source, null=True, blank=True)
    hyperlinks = models.ManyToManyField(Hyperlink, null=True, blank=True)
    user = models.ForeignKey('auth.User')

    def __unicode__(self):
        return self.sha256

    def get_absolute_url(self):
        return reverse_lazy('sample.list')

    class Meta:
        ordering = ['-created', '-updated']


class Description(TimeStampedModel):

    """
    This models saves descriptions of a sample.
    A sample can have multiple descriptions.
    """

    text = models.TextField()
    sample = models.ForeignKey(Sample)
    user = models.ForeignKey('auth.User')

    def __unicode__(self):
        return self.text

    class Meta:
        ordering = ['-created']


class AccessLog(TimeStampedModel):

    """
    This models saves logs when users download samples.
    """

    sample = models.ForeignKey(Sample)
    user = models.ForeignKey('auth.User')

    def __unicode__(self):
        return 'Access log #{0}'.format(self.id)

    class Meta:
        ordering = ['-created']

samples/views.py
# -*- coding: utf-8 -*-
import logging

from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.contrib import messages

from core.mixins import OwnerRequiredMixin
from core.mixins import LoginRequiredMixin
from core.mixins import UserRequiredFormMixin

from samples.utils import SampleHelper
from samples.models import Source
from samples.models import Sample
from samples.models import Filename
from samples.models import Hyperlink
from samples.models import Description
from samples.models import AccessLog
from samples.forms import SampleUploadForm
from samples.forms import SampleFilterForm
from samples.forms import SourceForm
from samples.forms import SourceAppendForm
from samples.forms import SourceRemoveForm
from samples.forms import FilenameAppendForm
from samples.forms import FilenameRemoveForm
from samples.forms import HyperlinkAppendForm
from samples.forms import HyperlinkRemoveForm
from samples.forms import DescriptionForm
from samples.mixins import SampleInitialFormMixin


logger = logging.getLogger(__name__)


class SourceListView(ListView, LoginRequiredMixin):

    """
    ListView for Source
    """

    model = Source
    template_name = 'source/list.html'

    def get_queryset(self):
        # users can see sample sources that owned by themself
        return self.model.objects.filter(user=self.request.user)


class SourceCreateView(CreateView, LoginRequiredMixin):

    """
    A class-based view for creating sample source.
    """

    model = Source
    fields = ['name', 'link', 'descr']
    form_class = SourceForm
    template_name = 'source/create.html'
    success_url = reverse_lazy('source.list')

    def form_valid(self, form):
        # Saving the user who creates the source
        form.instance.user = self.request.user
        messages.success(self.request, 'Source created.')
        return super(SourceCreateView, self).form_valid(form)


class SourceUpdateView(UpdateView, OwnerRequiredMixin):

    """
    UpdateView for Source.
    Users can update a source which owned by himself.
    """

    model = Source
    fields = ['name', 'link', 'descr']
    form_class = SourceForm
    template_name = 'source/update.html'

    def get_success_url(self):
        source = self.get_object()
        return reverse_lazy('source.detail', kwargs={'pk': source.pk})

    def form_valid(self, form):
        messages.success(self.request, 'Source details updated.')
        return super(SourceUpdateView, self).form_valid(form)


class SourceDeleteView(DeleteView, OwnerRequiredMixin):

    """
    DeleteView for Source.
    """

    model = Source
    template_name = 'source/delete.html'
    success_url = reverse_lazy('source.list')

    def form_valid(self, form):
        messages.success(self.request, 'Source deleted.')
        return super(SourceDeleteView, self).form_valid(form)


class SourceDetailView(DetailView, LoginRequiredMixin):

    """
    DetailView for Source.
    """

    model = Source
    template_name = 'source/detail.html'


class SampleUpdateBaseView(FormView):

    """
    A base view class for updating sample.
    """

    def get_success_url(self):
        """
        If sample updated, then the view will be redirect to the following URL.
        """
        return reverse_lazy(
            'sample.update',
            kwargs={'sha256': self.sample.sha256}
        )


class SourceAppendView(SampleUpdateBaseView, UserRequiredFormMixin,\
                        SampleInitialFormMixin, OwnerRequiredMixin):

    """
    Building a relationship between a Sample and a Source.
    """

    template_name = 'sample/append_source.html'
    form_class = SourceAppendForm

    def form_valid(self, form):
        self.sample, result = form.append()
        if not result:
            messages.error(
                self.request,
                'Failed to append Source. Source already exists.'
            )
        else:
            messages.success(self.request, 'Source appended.')
        return super(SourceAppendView, self).form_valid(form)


class SourceRemoveView(SampleUpdateBaseView, UserRequiredFormMixin,\
                        SampleInitialFormMixin, OwnerRequiredMixin):

    """
    This class just breaks the relationship between a Source and a Sample.
    """

    template_name = 'sample/remove.html'
    form_class = SourceRemoveForm

    def get_object(self):
        """
        Trying to get the Source by self.kwargs['source_pk'].
        """
        try:
            source = Source.objects.get(id=self.kwargs['source_pk'])
        except Source.DoesNotExist:
            raise Http404
        else:
            return source

    def get_initial(self):
        """
        Returning a dict that would be initial values for the form_class.
        """
        initial = super(SourceRemoveView, self).get_initial()
        initial['source'] = self.get_object().pk
        return initial

    def form_valid(self, form):
        self.sample, result = form.remove()
        if not result:
            messages.error(self.request, 'Failed to remove the source.')
        else:
            messages.success(self.request, 'Source removed.')
        return super(SourceRemoveView, self).form_valid(form)


class FilenameAppendView(SampleUpdateBaseView, UserRequiredFormMixin,\
                            SampleInitialFormMixin):

    """
    Building a relationship between a Sample and a Filename.
    """

    template_name = 'sample/append_filename.html'
    form_class = FilenameAppendForm

    def form_valid(self, form):
        self.sample, result = form.append()
        if not result:
            messages.error(self.request, 'Failed to append the filename.')
        else:
            messages.success(self.request, 'Filename appended.')
        return super(FilenameAppendView, self).form_valid(form)


class FilenameRemoveView(SampleUpdateBaseView, UserRequiredFormMixin,\
                            SampleInitialFormMixin, OwnerRequiredMixin):
    """
    This class just breaks the relationship between a Filename and a Sample.
    """

    template_name = 'sample/remove.html'
    form_class = FilenameRemoveForm

    def get_object(self):
        """
        Trying to get the Filename by self.kwargs['filename_pk'].
        """
        try:
            filename = Filename.objects.get(id=self.kwargs['filename_pk'])
        except Filename.DoesNotExist:
            raise Http404
        else:
            return filename

    def get_initial(self):
        """
        Returning a dict that would be initial values for the form_class.
        """
        initial = super(FilenameRemoveView, self).get_initial()
        initial['filename'] = self.get_object().pk
        return initial

    def form_valid(self, form):
        self.sample, result = form.remove()
        if not result:
            messages.error(self.request, 'Failed to remove the filename.')
        else:
            messages.success(self.request, 'Filename appended.')
        return super(FilenameRemoveView, self).form_valid(form)


class FilenameDeleteView(DeleteView, OwnerRequiredMixin):

    """
    A class-based view for deleting a filename.
    This CBV not only breaks the relationship between a Filename and
    Samples but deletes the Filename from database.
    Only the owner can delete the filename which owned by himself.
    """

    model = Filename
    template_name = 'sample/delete.html'
    success_url = reverse_lazy('sample.list')

    def get_object(self, **kwargs):
        return self.model.objects.get(id=self.kwargs['pk'])

    def form_valid(self, form):
        messages.success(self.request, 'Filename deleted.')
        return super(FilenameDeleteView, self).form_valid(form)


class HyperlinkAppendView(SampleUpdateBaseView, UserRequiredFormMixin,\
                            SampleInitialFormMixin):

    """
    Building a relationship between a Sample and a Hyperlink.
    """

    template_name = 'sample/append_hyperlink.html'
    form_class = HyperlinkAppendForm

    def form_valid(self, form):
        self.sample, result = form.append()
        if not result:
            messages.error(self.request, 'Failed to append the Hyperlink.')
        else:
            messages.success(self.request, 'Hyperlink appended.')
        return super(HyperlinkAppendView, self).form_valid(form)


class HyperlinkRemoveView(SampleUpdateBaseView, UserRequiredFormMixin,\
                            SampleInitialFormMixin, OwnerRequiredMixin):
    """
    This class just breaks the relationship between a Filename and a Sample.
    """

    template_name = 'sample/remove.html'
    form_class = HyperlinkRemoveForm

    def get_object(self):
        """
        Trying to get the Hyperlink by self.kwargs['hyperlink_pk'].
        """
        try:
            hyperlink = Hyperlink.objects.get(id=self.kwargs['hyperlink_pk'])
        except Hyperlink.DoesNotExist:
            raise Http404
        else:
            return hyperlink

    def get_initial(self):
        """
        Returning a dict that would be initial values for the form_class.
        """
        initial = super(HyperlinkRemoveView, self).get_initial()
        initial['hyperlink'] = self.get_object().pk
        return initial

    def form_valid(self, form):
        self.sample, result = form.remove()
        if not result:
            messages.error(self.request, 'Failed to remove the hyperlink.')
        else:
            messages.success(self.request, 'Hyperlink appended.')
        return super(HyperlinkRemoveView, self).form_valid(form)

samples/templates/sample/append_filename.html
{% extends 'samples_app_base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="append">
</form>
{% endblock content %}

samples/templates/sample/append_hyperlink.html
{% extends 'samples_app_base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="append">
</form>
{% endblock content %}

samples/templates/sample/append_source.html
{% extends 'samples_app_base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="append">
</form>
{% endblock content %}

samples/templates/sample/detail.html
{% extends 'samples_app_base.html' %}
{% load virustotal %}
{% load crispy_forms_tags %}
{% block content %}

{% for filetype in object.filetypes.all %}
    {{ filetype }}<br />
{% endfor %}

{% for filename in object.filenames.all %}
    {{ filename.name }}<br />
{% endfor %}

{% for source in object.sources.all %}
    {{ source.name }}
{% endfor %}

{{ object.size }}<br />
{{ object.crc32 }}<br />
{{ object.md5 }}<br />
{{ object.sha1 }}<br />
{{ object.sha256 }}<br />
{{ object.sha512 }}<br />
{{ object.ssdeep }}<br />

{% for descr in object.description_set.all %}
    {{ descr.text }}<br />
{% endfor %}

{% for hyperlink in object.hyperlinks.all %}
    {{ hyperlink.headline }} {{ hyperlink.link }}<br />
{% endfor %}

<a href="{{ object.sha256 | virustotal_link}}">VirusTotal</a><br />
<a href='{% url 'sample.update' object.sha256 %}'>update<br />
{% endblock content %}

samples/templates/sample/list.html
{% extends 'samples_app_base.html' %}
{% load virustotal %}
{% block content %}
<br />
<form action='' method='post'>
    {% csrf_token %} {{ filter_form.as_p }}
    <input type='submit' name='submit' value='submit'>
</form>

{% for object in object_list %}

    {{ object.md5 }}<br />

    {% for filename in object.filenames.all %}
        {{ filename }}<br />
    {% endfor %}
    {% for filetype in object.filetypes.all %}
        {{ filetype.detector }} {{ filetype.filetype }}<br />
    {% endfor %}

    <a href='{{ object.sha256 | virustotal_link}}'>VirusTotal</a><br />
    <a href='{% url 'sample.update' object.sha256 %}'>update<br />
    <a href='{% url 'sample.detail' object.sha256 %}'>detail<br />
    <a href='{% url 'sample.delete' object.sha256 %}'>delete</a><br />
    <a href='{% url 'sample.download' object.sha256 %}'>download</a><br />
    <br />
{% empty %}
{% endfor %}

{% endblock content %}

samples/templates/sample/remove.html
{% extends 'samples_app_base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Remove">
</form>
{% endblock content %}

samples/templates/sample/update.html
{% extends 'samples_app_base.html' %}
{% load virustotal %}
{% load crispy_forms_tags %}
{% block content %}

{% for filetype in object.filetypes.all %}
    {{ filetype }}<br />
{% endfor %}

{% for filename in object.filenames.all %}
    {{ filename.name }}
    {% if filename.user == request.user %}
        <a href="{% url 'filename.remove' object.sha256 filename.pk %}">remove</a>
        <a href="{% url 'filename.delete' filename.pk %}">delete</a><br />
    {% endif %}
{% endfor %}
<a href="{% url 'filename.append' object.sha256 %}">add</a><br />

{% for source in object.sources.all %}
    {{ source.name }}
    {% if source.user == request.user %}
        <a href="{% url 'source.remove' object.sha256 source.pk %}">remove</a><br />
    {% endif %}
{% endfor %}
<a href="{% url 'source.append' object.sha256 %}">add</a><br />


{{ object.size }}<br />
{{ object.crc32 }}<br />
{{ object.md5 }}<br />
{{ object.sha1 }}<br />
{{ object.sha256 }}<br />
{{ object.sha512 }}<br />
{{ object.ssdeep }}<br />

{% for descr in object.description_set.all %}
    {{ descr.text }}
    {% if descr.user == request.user %}
        <a href="{% url 'descr.update' descr.pk %}">update</a>&nbsp;
        <a href="{% url 'descr.delete' descr.pk %}">delete</a><br />
    {% endif %}
{% endfor %}
<a href="{% url 'descr.create' object.sha256 %}">add</a><br />

{% for hyperlink in object.hyperlinks.all %}
    {{ hyperlink.headline }} {{ hyperlink.link }}&nbsp;
    {% if hyperlink.user == request.user %}
        <a href="{% url 'hyperlink.remove' object.sha256 hyperlink.pk %}">remove</a>&nbsp;
        <a href="{% url 'hyperlink.delete' hyperlink.pk %}">delete</a><br />
    {% endif %}
{% endfor %}
<a href="{% url 'hyperlink.append' object.sha256 %}">add</a><br />


<a href="{{ object.sha256 | virustotal_link}}">VirusTotal</a><br />

{% endblock content %}

samples/templates/sample/update_description.html
{% extends 'samples_app_base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="update">
</form>
{% endblock content %}

samples/templates/sample/upload.html
{% extends 'samples_app_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% crispy form %}
</form>
{% endblock content %}